services:
    apisec-web-proxy:
        build:
          context: ./.docker/nginx
          dockerfile: Dockerfile
        restart: "unless-stopped"
        container_name: apisec-web-proxy
        hostname: apisec-web-proxy
        volumes:
            - ./src/public:/app/src/public
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "20090:80"
        depends_on:
            - apisec-web-ba
        networks:
          apisec-web-network:
            ipv4_address: 10.20.20.2

    apisec-web-ba:
        restart: "unless-stopped"
        container_name: apisec-web-ba
        hostname: apisec-web-ba
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
        volumes:
            - ./src:/app/src
        ports:
            -   "29010:9000"
        depends_on:
            - apisec-web-db
            - apisec-web-rd
        networks:
          apisec-web-network:
            ipv4_address: 10.20.20.3

    apisec-web-db:
      image: mysql:8.0.25
      restart: "unless-stopped"
      container_name: apisec-web-db
      hostname: apisec-web-db
      env_file:
        - ./.env
      ports:
        - '23306:3306'
      expose:
        - '3306'
      networks:
        apisec-web-network:
          ipv4_address: 10.20.20.4
      volumes:
          - apisec-web-db-data:/var/lib/mysql
          - .docker/db:/db

    apisec-web-rd:
      image: docker.io/bitnami/redis:7.0
      container_name: "apisec-web-rd"
      environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      ports:
        - '26279:6379'
      networks:
         apisec-web-network:
           ipv4_address: 10.20.20.5

      volumes:
        - apisec-web-rd-data:/bitnami/redis/data

networks:
  apisec-web-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.20.0.0/16"

volumes:
    apisec-web-db-data:
    apisec-web-rd-data:
