name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    #tags:
    #  - 'v\d+'
  #pull_request:
  #  branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Debug Event
        run: |
          echo "Triggered by actor: ${{ github.actor }}"

      - name: Generate .env file for laravel
        run: |
          echo "${{ secrets.APP_CONFIG }}" > .env
          echo "${{ secrets.LOG_CONFIG }}" >> code/.env
          echo "${{ secrets.MAIL_CONFIG }}" >> code/.env
          echo "${{ secrets.REDIS_CONFIG }}" >> code/.env
          echo "${{ secrets.SESSION_CONFIG }}" >> code/.env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> code/.env
          echo "DB_HOST=${{ secrets.MYSQL_DATABASE }}" >> code/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> code/.env
          echo "DB_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> code/.env
          echo "DB_USER=${{ secrets.MYSQL_USER }}" >> code/.env
          echo "DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> code/.env
          


      - name: Generate .env file for MySql Docker
        run: |
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" > .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          

      - name: Build project
        run: make build

      - name: start server
        run: make start

      - name: Install dependencies
        run: make app-run

      #- name: Exec Migrations
      #  run: make migrate

      #- name: Exec Migrations
      #  run: make app-test

      - name: Install Java for SonarQube
        run: sudo apt-get install -y openjdk-11-jre

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECTKEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}


      - name: Dependabot metadata
        if: github.actor == 'dependabot[bot]'
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GIT_TOKEN }}

      - name: Compress project
        run: zip -r api.zip . -x ".git*" "tests*" "*.github*"

      - name: Deploy to Donweb
        env:
          SSH_KEY: ${{ secrets.KEY_SSH_PRIVATE }}
          SSH_PUBLIC: ${{ secrets.KEY_SSH_PUBLIC }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          echo "$SSH_PUBLIC" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          
          # Transfiere el archivo comprimido
          scp app.zip $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/app.zip
          
          # Inicia el despliegue en el servidor remoto
          ssh $SERVER_USER@$SERVER_IP << 'EOF'
          unzip -o api.zip -d /var/platform/apisec
          cd /var/platform/apisec
          make build
          make start
          make app-run
          make migrate
          rm -rf api.zip
          EOF

  #postman:
  #  needs: setup
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Run postman tests
  #      run: |
  #        npm install -g newman
  #        newman run https://api.postman.com/collections/${{ secrets.COLLECTION_ID }}?access_key=${{ secrets.POSTMAN_API_KEY }}
