name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4

    - name: Copy .env
      run: |
        cd ./src
        php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: |
        ls -lsa .
        cd ./src
        composer install --no-dev --optimize-autoloader --no-interaction

    - name: Generate key
      run: |
        ls -lsa .
        cd ./src
        php artisan key:generate

    - name: Directory Permissions
      run: |
        ls -lsa .
        cd ./src
        chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        cd ./src
        mkdir -p database
        touch database/database.sqlite

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        cd ./src
        php artisan test
